### ISSUE TITLE
Updating grammars fails with 'no such commit'

### ISSUE THREAD

**Issue by mxr** [asottile/babi-grammars#104]
```console
$ ./bin/download-syntax update 
Dart-Code/Dart-Code ... up to date!
MagicStack/MagicPython ... up to date!
PowerShell/EditorSyntax ... up to date!
WhereIsX/vscode-crystal-lang ... error: no such commit 582998d9645c65c46f033a8263d29fd0cb921d58
Traceback (most recent call last):
  File "/Users/mxr/src/asottile/babi-grammars/./bin/download-syntax", line 593, in <module>
    raise SystemExit(main())
  File "/Users/mxr/src/asottile/babi-grammars/./bin/download-syntax", line 587, in main
    return _update(only=args.only)
  File "/Users/mxr/src/asottile/babi-grammars/./bin/download-syntax", line 521, in _update
    branches_s = subprocess.check_output(branches_cmd).decode()
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('git', '-C', '/var/folders/mg/2_7nx7493qg0vn9jhdp951tw0000gp/T/tmpmo6vtglu', 'branch', '-r', '--contains', '582998d9645c65c46f033a8263d29fd0cb921d58')' returned non-zero exit status 129.
```

When I view the commit on the GitHub UI I see "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

**Comment by asottile** [comment]
ah, we rebased this -- probably needs to point to the latest commit on this branch: https://github.com/WhereIsX/vscode-crystal-lang/tree/fix_crystal_grammar
